Site/Code/ACHE.Admin/Controllers/ReporteController.cs
using ACHE.Admin.Models;
using ACHE.Model;
using ACHE.Model.ViewModels;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ACHE.Admin.Controllers
{
    public class ReporteController : Controller
    {
        //
        // GET: /Reporte/
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult RptUsuarios(int idPlan = 0, string estado = "")
        {
            if (idPlan > 0 && !string.IsNullOrWhiteSpace(estado))
            {
                var model = new PlanesViewModel();
                model.Estado = estado;
                switch (idPlan)
                {
                    case 1:
                        model.Plan = "Basico";
                        break;
                    case 2:
                        model.Plan = "Profesional";
                        break;
                    case 3:
                        model.Plan = "Pyme";
                        break;
                    case 4:
                        model.Plan = "Empresa";
                        break;
                    case 5:
                        model.Plan = "Corporativo";
                        break;
                    case 6:
                        model.Plan = "Prueba";
                        break;
                    case 99:
                        model.Plan = "Free";
                        break;
                }
                return View(model);
            }
            else
                return View();
        }

        [HttpPost]
        public ActionResult ObtenerRptUsuarios(string integraciones, string periodo,
        string fechaDesde, string fechaHasta, string metodoDePago, string formaDePago, string tipoPlan, string codigoPromo, string estadoUsuario, int page, int pageSize)
        {
            ResultadosUsuarioViewModel resultado = new ResultadosUsuarioViewModel();
            try
            {

                var fecha = DateTime.Now.Date;

                using (var dbContext = new ACHEEntities())
                {
                    var results = dbContext.AdminRptUsuariosView.Where(x => x.TipoUsuario != "Adicional")
                        .OrderByDescending(x => x.FechaAlta).AsQueryable();

                    switch (periodo)
                    {
                        case "30":
                            fechaDesde = DateTime.Now.AddDays(-30).ToShortDateString();
                            break;
                        case "15":
                            fechaDesde = DateTime.Now.AddDays(-15).ToShortDateString();
                            break;
                        case "7":
                            fechaDesde = DateTime.Now.AddDays(-7).ToShortDateString();
                            break;
                        case "1":
                            fechaDesde = DateTime.Now.AddDays(-1).ToShortDateString();
                            break;
                        case "0":
                            fechaDesde = DateTime.Now.ToShortDateString();
                            break;
                    }

                    if (fechaDesde != string.Empty)
                    {
                        DateTime dtDesde = DateTime.Parse(fechaDesde);
                        results = results.Where(x => x.FechaUltLogin >= dtDesde).AsQueryable();
                    }
                    if (fechaHasta != string.Empty)
                    {
                        DateTime dtHasta = DateTime.Parse(fechaHasta + " 23:59:59 pm");
                        results = results.Where(x => x.FechaUltLogin <= dtHasta).AsQueryable();
                    }

                    if (integraciones != string.Empty)
                        results = results.Where(x => x.TieneIntegracion.ToUpper() == integraciones.ToUpper()).AsQueryable();

                    if (metodoDePago != string.Empty)
                        results = results.Where(x => x.FormaDePago.ToUpper() == metodoDePago.ToUpper()).AsQueryable();

                    if (formaDePago != string.Empty)
                        results = results.Where(x => x.PagoAnual == (formaDePago == "0" ? false : true)).AsQueryable();


                    if (!string.IsNullOrWhiteSpace(tipoPlan))
                    {
                        results = results.Where(x => x.PlanActual.ToUpper() == tipoPlan.ToUpper()).AsQueryable();
                    }

                    if (!string.IsNullOrWhiteSpace(codigoPromo))
                    {
                        results = results.Where(x => x.CodigoPromo.ToUpper().Contains(codigoPromo.ToUpper())).AsQueryable();
                    }

                    switch (estadoUsuario)
                    {
                        case "Setup OK":
                        case "Total Activos":
                            results = results.Where(x => x.Activo == true && x.Estado == "Aceptado" && x.FechaFinPlan >= fecha).AsQueryable();
                            break;
                        case "Dados de baja":
                            results = results.Where(x => x.Activo == false).AsQueryable();
                            break;
                        case "Total Usuarios":
                        default:
                            results = results.AsQueryable();
                            break;
                    }


                    page--;

                    resultado.TotalPage = ((results.Count() - 1) / pageSize) + 1;
                    resultado.TotalItems = results.Count();

                    var list = results.Skip(page * pageSize).Take(pageSize).ToList()
                        .Select(x => new UsuarioViewModel()
                        {
                            ID = x.IDUsuario,
                            IDPadre = x.IDUsuarioPadre ?? 0,
                            RazonSocial = x.RazonSocial,
                            AntiguedadMeses = x.AntiguedadMeses ?? 0,
                            CodigoPromo = x.CodigoPromo ?? "",
                            PlanActual = x.PlanActual,
                            Email = x.Email,
                            FechaDeBaja = x.FechaBaja.HasValue ? x.FechaBaja.Value.ToString("dd/MM/yyyy") : ""
                        }).ToList();
                    resultado.Items = list.ToList();
                }
            }
            catch (Exception ex)
            {
                return Json(false, JsonRequestBehavior.AllowGet);
            }
            return Json(resultado, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult exportRptUsuarios(string integraciones, string periodo,
        string fechaDesde, string fechaHasta, string metodoDePago, string formaDePago, string tipoPlan, string codigoPromo, string estadoUsuario)
        {
            string fileName = "Usuarios";
            string path = "~/tmp/";

            var fecha = DateTime.Now.Date;


            try
            {
                DataTable dt = new DataTable();
                using (var dbContext = new ACHEEntities())
                {
                    var results = dbContext.AdminRptUsuariosView.OrderByDescending(x => x.FechaAlta).AsQueryable();//Obtengo todos los usuarios padres e hijos.
                    switch (periodo)
                    {
                        case "30":
                            fechaDesde = DateTime.Now.AddDays(-30).ToShortDateString();
                            break;
                        case "15":
                            fechaDesde = DateTime.Now.AddDays(-15).ToShortDateString();
                            break;
                        case "7":
                            fechaDesde = DateTime.Now.AddDays(-7).ToShortDateString();
                            break;
                        case "1":
                            fechaDesde = DateTime.Now.AddDays(-1).ToShortDateString();
                            break;
                        case "0":
                            fechaDesde = DateTime.Now.ToShortDateString();
                            break;
                    }

                    //Filtro los usuarios padres e hijos que cumplan las condiciones
                    if (fechaDesde != string.Empty)
                    {
                        DateTime dtDesde = DateTime.Parse(fechaDesde);
                        results = results.Where(x => x.FechaUltLogin >= dtDesde).AsQueryable();
                    }
                    if (fechaHasta != string.Empty)
                    {
                        DateTime dtHasta = DateTime.Parse(fechaHasta + " 23:59:59 pm");
                        results = results.Where(x => x.FechaUltLogin <= dtHasta).AsQueryable();
                    }

                    if (integraciones != string.Empty)
                        results = results.Where(x => x.TieneIntegracion.ToUpper() == integraciones.ToUpper()).AsQueryable();

                    if (metodoDePago != string.Empty)
                        results = results.Where(x => x.FormaDePago.ToUpper() == metodoDePago.ToUpper()).AsQueryable();

                    if (formaDePago != string.Empty)
                        results = results.Where(x => x.PagoAnual == (formaDePago == "0" ? false : true)).AsQueryable();

                    if (!string.IsNullOrWhiteSpace(tipoPlan))
                    {
                        results = results.Where(x => x.PlanActual.ToUpper() == tipoPlan.ToUpper()).AsQueryable();
                    }

                    if (!string.IsNullOrWhiteSpace(codigoPromo))
                    {
                        results = results.Where(x => x.CodigoPromo.ToUpper().Contains(codigoPromo.ToUpper())).AsQueryable();
                    }

                    switch (estadoUsuario)
                    {
                        case "Setup OK":
                        case "Total Activos":

Site/Code/ACHE.Admin/Controllers/SoporteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ACHE.Model;
using ACHE.Extensions;
using ACHE.Admin.Models;
using System.Configuration;
using System.Collections.Specialized;
using System.Data;
using System.IO;
using ACHE.Negocio.Facturacion;
using ACHE.Model.Negocio;
using Hangfire;
using ACHE.Negocio.Contabilidad;
using ACHE.Negocio.Common;

namespace ACHE.Admin.Controllers {
    public class SoporteController : BaseController {
        public ActionResult RecuperarCae() {
            return View();
        }

        public ActionResult RegenerarPdf() {
            return View();
        }

    }
}

Site/Code/ACHE.Admin/Views/Shared/_Header.cshtml
<div class="headerbar">
    <div class="header-left">
        <div class="logopanel">
            <a href="@Url.Action("Index", "Home")" style="color: #fff;font-size: 25px;">FIDELY</a>
        </div>
        <div class="topnav">
            <a class="menutoggle"><i class="fa fa-bars"></i></a>

            

            <ul class="nav nav-horizontal">
                <li class="nav-parent">

                    <a href="#"><i class="fa fa-tachometer"></i>DashBoard<span class="caret"></span></a>
                    <ul class="dropdown-menu children">
                        <li><a href='@Url.Action("Index", "Home")'><i class="fa fa-bar-chart"></i><span>DashBoard</span></a></li>
                    </ul>
                </li>



                <li><a href='@Url.Action("Index", "Usuario")'><i class="fa fa-users"></i><span>Usuarios</span></a></li>

                <li class="nav-parent">
                    <a href="#"><i class="fa fa-cog"></i>Soporte <span class="caret"></span></a>
                    <ul class="dropdown-menu children">
                        <li><a href='@Url.Action("RecuperarCae", "Soporte")'><i class="fa fa-caret-right"></i><span>Recuperar CAE</span></a></li>
                        <li><a href='@Url.Action("RegenerarPdf", "Soporte")'><i class="fa fa-caret-right"></i><span>Regenerar PDF</span></a></li>
                       
                    </ul>
                </li>

                <li class="nav-parent">
                    <a href="#"><i class="fa fa-bar-chart"></i>Reportes <span class="caret"></span></a>
                    <ul class="dropdown-menu children">
                        
                        <li><a href='@Url.Action("RptUsuarios", "Reporte")'><i class="fa fa-caret-right"></i><span>Usuarios</span></a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>

    <div class="header-right">
        <ul class="headermenu">
            <li>
                <div class="btn-group">
                    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" style="color: #fff">
                        <img src="~/images/photos/loggeduser.png" alt="" />
                        Admin
                        <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu dropdown-menu-usermenu pull-right">

                        <li><a href="@Url.Action("LogOut", "Account")"><i class="fa fa-sign-out"></i><span>Cerrar sesión</span></a></li>
                    </ul>
                </div>
            </li>
        </ul>
    </div>
</div>

Site/Code/ACHE.Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml" lang="es-ar">
<head id="Head1" runat="server">
    <title>Fidely</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />
    <meta name="description" content="" />
    <link rel="shortcut icon" href="/images/favicon.png" type="image/png" />
    <link href="~/css/style.default.css" rel="stylesheet" />
    <link href="~/css/style.inverse.css" rel="stylesheet" />
    @*<link rel="stylesheet" href="/font-awesome/css/font-awesome.min.css" />*@
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" />
    @*<link href="css/font.helvetica-neue.css" rel="stylesheet" />*@
    <script src="~/js/jquery-1.11.1.min.js"></script>
    <script src="~/js/jquery-migrate-1.2.1.min.js"></script>
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
        <script src="~/js/html5shiv.js"></script>
        <script src="~/js/respond.min.js"></script>
    <![endif]-->
    <style type="text/css">
        .table thead > tr > th, .table tbody > tr > th, .table tfoot > tr > th, .table thead > tr > td, .table tbody > tr > td, .table tfoot > tr > td {
            padding:5px
        }

    </style>
</head>
<body class="horizontal-menu stickyheader">

    <div id="preloader">
        <div id="status"><i class="fa fa-spinner fa-spin"></i></div>
    </div>

    <section>
        <div class="leftpanel">
            <div class="logopanel">
                <h1>FIDELY</h1>
            </div>
            <div class="leftpanelinner">

                <!-- This is only visible to small devices -->
                <div class="visible-xs hidden-sm hidden-md hidden-lg">
                    <div class="media userlogged">
                        <img alt="" src="~/images/photos/loggeduser.png" class="media-object" />
                        <div class="media-body">
                            <h4>Admin</h4>
                            @*<span>"Life is so..."</span>*@
                        </div>
                    </div>

                    <h5 class="sidebartitle actitle">Mi cuenta</h5>
                    <ul class="nav nav-pills nav-stacked nav-bracket mb30">
                        @*<li><a href="profile.html"><i class="fa fa-user"></i><span>Profile</span></a></li>
                        <li><a href=""><i class="fa fa-cog"></i><span>Account Settings</span></a></li>
                        <li><a href=""><i class="fa fa-question-circle"></i><span>Help</span></a></li>
                        <li><a href="signout.html"><i class="fa fa-sign-out"></i><span>Sign Out</span></a></li>*@
                        <li><a href="@Url.Action("LogOut", "Account")"><i class="fa fa-sign-out"></i><span>Cerrar sesión</span></a></li>
                    </ul>
                </div>
                <h5 class="sidebartitle">Menú</h5>
                <ul class="nav nav-pills nav-stacked nav-bracket">
                   <li class="nav-parent">
                         <a href="#"><i class="fa fa-tachometer"></i>DashBoard<span class="caret"></span></a>
                        <ul class="dropdown-menu children">
                            <li><a href='@Url.Action("Index", "Home")'><i class="fa fa-bar-chart"></i><span>DashBoard</span></a></li>
                           
                        </ul>
                    </li>
                    <li><a href='@Url.Action("Index", "Usuario")'><i class="fa fa-users"></i><span>Usuarios</span></a></li>
                    <li><a href='@Url.Action("Index", "Facturacion")'><i class="fa fa-money"></i><span>Facturación</span></a></li>

                    <li class="nav-parent">
                        <a href="#"><i class="fa fa-cog"></i>Soporte <span class="caret"></span></a>
                        <ul class="dropdown-menu children">
                            <li><a href='@Url.Action("RecuperarCae", "Soporte")'><i class="fa fa-caret-right"></i><span>Recuperar CAE</span></a></li>
                            <li><a href='@Url.Action("RegenerarPdf", "Soporte")'><i class="fa fa-caret-right"></i><span>Regenerar PDF</span></a></li>
                            
                        </ul>
                    </li>
                    <li class="nav-parent">
                        <a href="#"><i class="fa fa-bar-chart"></i>Reportes <span class="caret"></span></a>
                        <ul class="dropdown-menu children">
                            
                            <li><a href='@Url.Action("RptUsuarios", "Reporte")'><i class="fa fa-caret-right"></i><span>Usuarios</span></a></li>

                        </ul>
                    </li>
                </ul>
            </div>
            <!-- leftpanelinner -->
        </div>

        <div class="mainpanel">
            @Html.Partial("~/Views/Shared/_Header.cshtml")

            @RenderBody()
        </div>
    </section>

    <script src="~/js/jquery-ui-1.10.3.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/modernizr.min.js"></script>
    <script src="~/js/jquery.numericInput.min.js"></script>
    <script src="~/js/toggles.min.js"></script>
    <script src="~/js/bootbox.js"></script>
    <script src="~/js/custom.js"></script>
    <script src="~/js/views/common.js?v=1"></script>

        <script type="text/javascript">
            setInterval(function () {
                // Do something every 5 seconds
                // 1. Make request to server
                var url = document.domain;
                $.post("/Account/KeepSession");
            }, 6000);
    </script>

</body>
</html>